clientejwt/Models/AuthUser.cs
namespace clientejwt.Models
{
    public class AuthUser
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Rol { get; set; }
        public string AccessToken { get; set; }
    }
}

clientejwt/Models/ErrorViewModel.cs
namespace clientejwt.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

clientejwt/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace clientejwt.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [EmailAddress(ErrorMessage = "El campo {0} no es una dirección de correo válida")]
        [Display(Name = "Correo electrónico")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
    }
}

clientejwt/Models/UsuarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace clientejwt.Models
{
    public class UsuarioViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [Display(Name = "Nombre")]
        public string Nombrecompleto { get; set; }
        public string Rol { get; set; }
    }
}

clientejwt/Controllers/CuentasController.cs
using clientejwt.Models;
using clientejwt.Service.Backend;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace clientejwt.Controllers
{
    [Authorize]
    public class CuentasController : Controller
    {
        private readonly IBackend _backend;

        public CuentasController(IBackend backend)
        {
            _backend = backend;
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginAsync(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var authUser = await _backend.AutenticacionAsync(model.Correo, model.Password);

                    if (authUser == null)
                    {
                        ModelState.AddModelError("Correo", "Credenciales no válidas. Inténtelo nuevamente.");
                    }
                    else
                    {
                        var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, authUser.Email),
                            new Claim(ClaimTypes.GivenName, authUser.Nombre),
                            new Claim(ClaimTypes.Email, authUser.Email),
                            new Claim("token", authUser.AccessToken),
                            new Claim(ClaimTypes.Role, authUser.Rol),
                        };

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var authProperties = new AuthenticationProperties();
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
                        return RedirectToAction("Index", "Home");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> PerfilAsync()
        {
            var token = User.FindFirstValue("token");
            var correo = User.FindFirstValue(ClaimTypes.Email);
            ViewData["token"] = User.FindFirstValue("token");

            var usuario = await _backend.GetUsuarioAsync(correo, token);

            return View(usuario);
        }

        public async Task<IActionResult> LogoutAsync(string returnUrl = null)
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

clientejwt/Controllers/HomeController.cs
using clientejwt.Models;
using clientejwt.Service.Backend;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;

namespace clientejwt.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBackend _backend;

        public HomeController(IBackend backend)
        {
            _backend = backend;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var token = User.FindFirstValue("token");
            var usuarios = await _backend.GetUsuariosAsync(token);
            return View(usuarios);
        }
        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

clientejwt/Views/Cuentas/Login.cshtml
@model LoginViewModel
@{
    ViewData["title"] = "Inicio de sesion";
}
<h1 class="h3 text-center text-success">Desarrollo de Sistemas Web</h1>
<h2 class="h5 text-center text-muted">Licenciatura en ingeniería de software</h2>
<form asp-action="Login">
    <div class="card mx-auto mt-3" style="max-width: 500px;">
        <div class="card-body">
            <h5 class="card-card-title text-center">@ViewData["Title"]</h5>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Correo" class="form-label"></label>
                <input asp-for="Correo" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

clientejwt/Views/Cuentas/Perfil.cshtml
@model UsuarioViewModel
@{
    ViewData["Title"] = "Perfil de usuario";
}

<h2 class="text-center mb-4">@ViewData["Title"]</h2>

<div class="card text-dark bg-light mt-3">
    <div class="card-header">
        @Model.Nombrecompleto
    </div>
    <div class="card-body">
        <div class="form-text mb-2">
            <div class="text-dark">@Html.DisplayNameFor(model => model.Email)</div>
            @Model.Email
        </div>
        <div class="form-text mb-2">
            <div class="text-dark">@Html.DisplayNameFor(model => model.Rol)</div>
            @Model.Rol
        </div>
    </div>
    <div class="card-footer small">
        @ViewData["token"]
    </div>
</div>

clientejwt/Views/Home/Index.cshtml
@model List<UsuarioViewModel>
@{
    ViewData["title"] = "Lista de usuario";
}


<h1 class="h3 text-center text-success">Desarrollo de Sistemas Web</h1>
<h2 class="h5 text-center text-muted">Licenciatura en ingeniería de software</h2>
@if (Model.Count() > 0)
{
    <h4 class="text-center mt-5 mb-3">Usuarios desde el backed</h4>
    <div class="table-responsive">
        <table class="table table-bordered small">
            <thead class="table-light">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Nombrecompleto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Email)
                    </th>
                    <th>
                        Roles
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <strong>@Html.DisplayFor(modelItem => item.Id)</strong>
                        </td>
                        <td>
                            <strong>@Html.DisplayFor(modelItem => item.Nombrecompleto)</strong>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Rol)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="mt-5">
        <div class="alert alert-warning" role="alert">
            No se ha podido conectar al backend. <a asp-controller="Cuentas" asp-action="Login">Iniciar sesión</a>
        </div>
    </div>
}

clientejwt/Views/Shared/AccessDenied.cshtml
@{
    ViewData["title"] = "Acceso denegado";
}

<div class="container my-2">
    <h1 class="text-danger">@ViewData["title"]</h1>
    <p class="text-muted">El usuario actual no tiene acceso a este apartado</p>
</div>

clientejwt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - clientejwt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/clientejwt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">clientejwt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - clientejwt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>